### ISSUE TITLE
Create a !topic command

### ISSUE THREAD

**Issue by egguy** [lyon-esport/LouisDeLaTech#1]
Add a `!topic <descript>` command to allow a person to change the topic of a chan.

**Comment by M0NsTeRRR** [comment]
You mean channel name or channel description ? or both

**Comment by egguy** [comment]
Description, for the channel use the current channel where it's typed (ala IRC ;) )

**Comment by M0NsTeRRR** [comment]
Fixed in 9d4bdf9996643e1df487f2a8906e72169a314471
