### ISSUE TITLE
Add new group member "Conseil d'Administration"

### ISSUE THREAD

**Issue by Emma0Z** [lyon-esport/LouisDeLaTech#13]
Please add "Conseil d'administration" as a new option into group for "CA" members only.
Discord group : `Membres du CA`

Also, please considerate some users are into "Conseil d'Administration" but also into a team.
eq : Vincent SERELLE (Equipe Technique, Membres du CA, Responsable Technique)

**Comment by M0NsTeRRR** [comment]
Responsable Technique will be not managed by the bot, only default role and teams

**Comment by M0NsTeRRR** [comment]
Implemented in abbe3a1, CA role will be managed manually (can't be updated by uteam, provision) also a new variable was added "team_role" for each team to prevent gsuite signature email to show team CA.

I close the issue, if you found a bug, open a new issue
