### ISSUE TITLE
Password sometimes bug

### ISSUE THREAD

**Issue by M0NsTeRRR** [lyon-esport/LouisDeLaTech#158]
Markdown escaping not working properly maybe ?

**Comment by M0NsTeRRR** [comment]
Also we should send an hashed password instead of the clear text password according to [documentation](https://developers.google.com/admin-sdk/directory/reference/rest/v1/users#User)

**Comment by egguy** [comment]
Could there be an interaction with the HTML escape of jinja2 + markdown escape ? Perhaps it needs to mark the string as |safe ? (if it exists in jinja2 template)
